### ISSUE TITLE
usage of chal in finish 

### ISSUE THREAD

**Issue by udf2457** [stef/libsphinx#18]
My c knowledge is not the greatest, but I can't seem to understand what `chal` is doing as an input to `sphinx_finish` ?

As far as I can see it is only used twice, once in a debug `dump` and once in `memcmp`. So unless I've missed it, it seems to have no meaningful use ?

**Comment by stef** [comment]
the memcmp is important. it checks that the response is not equal to the challenge.

**Comment by stef** [comment]
but, this whole lib will be replaced with liboprf in sphinx v2.0 - to 1/ be conformant with the IRTF/CFRG OPRF spec and to 2/ allow the threshold setup.

**Comment by stef** [comment]
pls close this issue if it answers your question.
