### ISSUE TITLE
Python dependency

### ISSUE THREAD

**Issue by micwoj92** [stef/libsphinx#19]
Hello, is the python dependency mentioned in readme still needed?

I tried to `make bin libsphinx.so tests/sphinx` with and without python and I can't see difference between two, so I concluded it was not needed. I think that it's the case since commit https://github.com/stef/libsphinx/commit/ece30d6df8d7508d54c2d67a2e25502516c8a8d5

**Comment by stef** [comment]
indeed, for this lib python is not needed anymore.

**Comment by stef** [comment]
thank you for noticing!
