### ISSUE TITLE
Security parameters for OPAQUE

### ISSUE THREAD

**Issue by baryluk** [stef/libsphinx#4]
It is not mentioned what curves, key lengths, hash functions, hash lengths, hash iterations, and other security parameters are used, or what source of randomness is used.

**Comment by stef** [comment]
what else would you like to have documented? https://github.com/stef/libsphinx/commit/89c822aa75d3bd1723822b12c928ba6f3a1166c2 - if you agree this solves this issue, please close it. thanks a lot for this valuable request.

**Comment by baryluk** [comment]
Looks nice. Thanks!
