### ISSUE TITLE
Error while making

### ISSUE THREAD

**Issue by skurzhanskyi** [stef/libsphinx#5]
when I try to use makefile I get this error:
![image](https://user-images.githubusercontent.com/17638837/48620270-34897000-e9a8-11e8-8cf7-7d9787d5f2c1.png)
can you help, please?

**Comment by stef** [comment]
libsodium is missing, please read https://github.com/stef/libsphinx#installing

**Comment by skurzhanskyi** [comment]
`libsodium` is installed 
`pysodium` also has such a dependency and works fine

**Comment by skurzhanskyi** [comment]
Thanks. Just last question: is it possible to install `libsodium-dev` on OSx. Didn't find anything.

**Comment by stef** [comment]
dunno about osx. but you need the headers from libsodium. you can specify their location by providing `-I<path to headers> when calling gcc

**Comment by skurzhanskyi** [comment]
thanks a lot, that solved my problem
